- name: copy grafana libarary
  copy:
    src: "{{ playbook_dir }}/files/grafana/lib/grafana-8.5.6-1.x86_64.rpm"
    dest: /opt/grafana.rpm
    owner: root
    group: root

- name: Install Grafana
  yum: 
    name: /opt/grafana.rpm
    state: present

- name: Start Grafana
  systemd:
    name: grafana-server
    state: started
    enabled: yes
    daemon_reload: yes
