---
- name: Install elastic
  include: install_elastic.yml

- name: Set up elastic init master
  include: setup_elastic_master.yml
  when:
    - master_ip is undefined

- name: Set up elastic slave
  include: setup_elastic_slave.yml  
  when:
    - master_ip is defined
