---
- name: format disk
  shell: |
    declare device
    device=$(lsblk -o NAME,SIZE,UUID | grep {{ attach_disk_size }} | tail -1 | cut -d ' ' -f 1)
    echo y | mkfs.ext4 -m 0 -E lazy_itable_init=0,lazy_journal_init=0,discard /dev/$device
    mkdir -p {{ path_data }}
    mount -o discard,defaults /dev/sdb {{ path_data }}
    chmod a+w {{ path_data }}
    cp /etc/fstab /etc/fstab.backup
    declare uuid
    uuid=$(blkid -s UUID /dev/$device | cut -d '"' -f 2)
    echo "UUID=$uuid {{ path_data }} ext4 discard,defaults,nofail 0 2" >> /etc/fstab

- name: restart host
  shell: sleep 1;/usr/sbin/reboot
  async: 1
  poll: 0
  ignore_errors: true

- name: waiting for host to start
  wait_for_connection:
    delay: 10

- name: check disk status
  shell: "lsblk -o NAME,MOUNTPOINT | grep sdb | grep elasticsearch | cut -d '/' -f 3"
  register: disk_status
  until: disk_status.stdout.find("elasticsearch") != -1
