- name: Install Java-1.8.0
  yum: 
    name: java-1.8.0-openjdk-devel 
    state: latest

- name: Copy Jenkins Libarary
  copy:
    src: "{{ playbook_dir }}/files/jenkins/lib/jenkins-2.346.3-1.1.noarch.rpm"
    dest: /opt/jenkins.rpm
    owner: root
    group: root

- name: Install Jenkins
  yum: 
    name: /opt/jenkins.rpm
    state: present

- name: Start jenkins
  systemd:
    name: jenkins
    state: started
    enabled: yes
    daemon_reload: yes